SERVER_PORT:
ENDPOINT_URL:
ENDPOINT_PORT:
HEADERS:
  Access-Control-Allow-Origin: '*'
  Access-Control-Allow-Methods: 'PUT, GET, POST, DELETE, OPTIONS'
  Access-Control-Allow-Headers:
    'Accept,
    Content-Type,
    Origin,
    X-Requested-With'
